/*
 * Made with all the love in the world
 * by scireum in Remshalden, Germany
 *
 * Copyright by scireum GmbH
 * http://www.scireum.de - info@scireum.de
 */

package sirius.pasta.noodle;

import sirius.pasta.noodle.compiler.ir.Node;

import javax.annotation.Nullable;
import java.lang.reflect.Type;

/**
 * Represents a compiled <tt>Noodle</tt> script which can be called within an {@link Environment}.
 * <p>
 * We hide the concrete implementation behind an interface here, as some simple scripts can easily
 * be reduced to a simple Java method like returning a constant or an i18n text.
 */
public interface Callable {

    /**
     * Determines the return type of the value generated by this script.
     *
     * @return the class of the object being returned by this script
     */
    Class<?> getType();

    /**
     * Returns the generic {@link Type} being returned by this script.
     * <p>
     * This is required to propagate concrete classes for generics.
     *
     * @see Node#getGenericType()
     */
    Type getGenericType();

    /**
     * Invokes the script within the given environment.
     *
     * @param environment the environment used to access shared variables
     * @return the result of the script
     * @throws ScriptingException in case of an error within the script. See {@link ScriptingException} for a detailed
     *                            explanation of when this exception is used.
     */
    @Nullable
    Object call(Environment environment) throws ScriptingException;
}
