/*
 * Made with all the love in the world
 * by scireum in Remshalden, Germany
 *
 * Copyright by scireum GmbH
 * http://www.scireum.de - info@scireum.de
 */

package sirius.pasta.noodle;

/**
 * Defines an environment which permits to access shared variables.
 * <p>
 * For example a <b>Tagliatelle</b> template is a bunch of scripts which share all arguments and local variables
 * of the template. Therefore, an environment (in the form of {@link sirius.pasta.tagliatelle.rendering.LocalRenderContext}
 * is provided to share these.
 */
public interface Environment {

    /**
     * Reads the shared variable with the given index.
     * <p>
     * Note that these indices are best generated by a {@link sirius.pasta.noodle.compiler.VariableScoper}
     * which takes care of visibilities etc.
     *
     * @param index the index of the shared variable to access
     * @return the value of the variable
     */
    Object readVariable(int index);

    /**
     * Stores the given value for the given shared variable.
     *
     * @param index the index of the variable to store
     * @param value the value to store
     */
    void writeVariable(int index, Object value);
}
