scireum_volumes: &scireum_volumes
  - /var/run/docker.sock:/var/run/docker.sock
  - /var/repos/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:/drone/src/github.com/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
  - /root/.m2:/root/.m2
  - /root/.gnupg:/root/.gnupg
clone:
  git:
    image: plugins/git
    volumes: *scireum_volumes
pipeline:
  compile:
    image: scireum/sirius-build
    commands:
      - mvn clean compile
    volumes: *scireum_volumes
    when:
      event: push
  test:
    image: scireum/sirius-build
    commands:
      - mvn clean test
    volumes: *scireum_volumes
    when:
      event: pull_request
  sonar:
    image: scireum/sirius-build
    commands:
      - sed -i 's/DEVELOPMENT-SNAPSHOT/${DRONE_TAG}/g' pom.xml
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Dsonar.projectKey=${DRONE_REPO_NAME}
    volumes: *scireum_volumes
    when:
      event: tag
  deploy:
    image: scireum/sirius-build
    commands:
      - sed -i 's/DEVELOPMENT-SNAPSHOT/${DRONE_TAG}/g' pom.xml
      - mvn clean deploy -DskipTests
    volumes: *scireum_volumes
    when:
      event: tag
