/*
 * Made with all the love in the world
 * by scireum in Remshalden, Germany
 *
 * Copyright by scireum GmbH
 * http://www.scireum.de - info@scireum.de
 */

package sirius.pasta.tagliatelle;

import io.netty.handler.codec.http.HttpResponseStatus;
import sirius.kernel.Sirius;
import sirius.kernel.commons.Strings;
import sirius.kernel.commons.Tuple;
import sirius.kernel.di.GlobalContext;
import sirius.kernel.di.std.Part;
import sirius.kernel.di.std.Register;
import sirius.kernel.health.HandledException;
import sirius.pasta.noodle.compiler.CompileException;
import sirius.pasta.noodle.macros.Macro;
import sirius.pasta.tagliatelle.tags.TagHandlerFactory;
import sirius.web.controller.BasicController;
import sirius.web.controller.Routed;
import sirius.web.http.WebContext;
import sirius.web.security.Permission;

import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.util.Collection;
import java.util.Comparator;
import java.util.List;

/**
 * Provides a small helper to provide infos about available Tagliatelle tags.
 */
@Register
public class TagliatelleController extends BasicController {

    /**
     * Describes the permission required to access the Tagliatelle infos
     */
    public static final String PERMISSION_SYSTEM_TAGS = "permission-system-tags";

    /**
     * Describes the permission required to access the Tagliatelle state
     */
    public static final String PERMISSION_SYSTEM_TAGS_STATE = "permission-system-tags-state";

    @Part
    private Tagliatelle tagliatelle;

    @Part
    private GlobalContext context;

    @Override
    public void onError(WebContext webContext, HandledException error) {
        webContext.respondWith().error(HttpResponseStatus.INTERNAL_SERVER_ERROR, error);
    }

    /**
     * Renders a list of all known tags.
     *
     * @param webContext the request to process
     */
    @Routed("/system/tags")
    @Permission(PERMISSION_SYSTEM_TAGS)
    public void overview(WebContext webContext) {
        Collection<Macro> macros =
                context.getParts(Macro.class).stream().sorted(Comparator.comparing(Macro::getName)).toList();
        Collection<String> builtIns = context.getParts(TagHandlerFactory.class)
                                             .stream()
                                             .map(TagHandlerFactory::getName)
                                             .map(name -> name.substring(2))
                                             .sorted()
                                             .toList();

        webContext.respondWith()
                  .template("/templates/system/tags.html.pasta",
                            macros,
                            builtIns,
                            tagliatelle.getTagLibs(),
                            tagliatelle.getTagLibTags());
    }

    /**
     * Renders all known tags/macros as markdown to aid external tooling.
     *
     * @param webContext the request to process
     * @throws IOException      in case of an I/O error while writing the response
     * @throws CompileException in case of an error while rendering the tag templates to extract their arguments
     */
    @Routed("/system/tags.md")
    public void markdownOverview(WebContext webContext) throws IOException, CompileException {
        if (!Sirius.isDev()) {
            // Only allow unauthenticated calls on local dev systems to ease external tool use.
            assertPermission(PERMISSION_SYSTEM_TAGS);
        }

        Collection<Macro> macros =
                context.getParts(Macro.class).stream().sorted(Comparator.comparing(Macro::getName)).toList();
        List<TagHandlerFactory> builtIns = context.getParts(TagHandlerFactory.class)
                                                  .stream()
                                                  .sorted(Comparator.comparing(TagHandlerFactory::getName))
                                                  .toList();
        List<Tuple<String, String>> tagLibs =
                tagliatelle.getTagLibs().stream().sorted(Comparator.comparing(Tuple::getFirst)).toList();

        StringBuilder markdown = new StringBuilder();
        markdown.append("# Tagliatelle Inventory\n\n");
        markdown.append("Generated by `/system/tags.md`.\n\n");

        markdown.append("## Macros\n\n");
        for (Macro macro : macros) {
            markdown.append("- `@").append(macro.getName()).append("`");
            if (Strings.isFilled(macro.getDescription())) {
                markdown.append(": ").append(macro.getDescription().replace('\n', ' '));
            }
            markdown.append('\n');
        }

        markdown.append("\n## Built-in i:* Tags\n\n");
        for (TagHandlerFactory handlerFactory : builtIns) {
            String builtInName = handlerFactory.getName().startsWith("i:") ?
                                 handlerFactory.getName().substring(2) :
                                 handlerFactory.getName();
            markdown.append("### `i:").append(builtInName).append("`\n\n");
            if (Strings.isFilled(handlerFactory.getDescription())) {
                markdown.append(handlerFactory.getDescription()).append("\n\n");
            }
            appendArgumentList(markdown, handlerFactory.reportArguments());
            markdown.append('\n');
        }

        markdown.append("## Taglibs\n\n");
        for (Tuple<String, String> tagLib : tagLibs) {
            String prefix = tagLib.getFirst();
            markdown.append("### `").append(prefix).append(":*`\n\n");
            markdown.append("- Description: ").append(tagLib.getSecond()).append('\n');

            List<String> tags = tagliatelle.getTagLibTags().get(prefix).stream().sorted().toList();
            for (String tag : tags) {
                Template template = tagliatelle.resolve("/taglib/" + prefix + "/" + tag + ".html.pasta")
                                               .orElseThrow(() -> new IllegalArgumentException(tag));
                markdown.append("\n#### `").append(prefix).append(':').append(tag).append("`\n\n");
                String description = template.getPragma("description").asString();
                if (Strings.isFilled(description)) {
                    markdown.append(description).append("\n\n");
                }
                appendArgumentList(markdown, template.getArguments());
            }

            markdown.append('\n');
        }

        try (OutputStream output = webContext.respondWith()
                                             .outputStream(HttpResponseStatus.OK, "text/markdown;charset=UTF-8");
             PrintWriter writer = new PrintWriter(new OutputStreamWriter(output, StandardCharsets.UTF_8))) {
            writer.print(markdown);
        }
    }

    private static void appendArgumentList(StringBuilder markdown, List<TemplateArgument> arguments) {
        if (arguments.isEmpty()) {
            markdown.append("- Arguments: _(none)_\n");
            return;
        }

        markdown.append("- Arguments:\n");
        for (TemplateArgument argument : arguments) {
            markdown.append("  - `")
                    .append(argument.getName())
                    .append("` (`")
                    .append(argument.getType().getSimpleName())
                    .append("`");
            if (argument.getDefaultValue() != null) {
                markdown.append(", optional");
            } else {
                markdown.append(", required");
            }
            markdown.append(')');
            if (Strings.isFilled(argument.getDescription())) {
                markdown.append(": ").append(argument.getDescription());
            }
            if (Strings.isFilled(argument.getDeprecationWarning())) {
                markdown.append(" (deprecated: ").append(argument.getDeprecationWarning()).append(')');
            }
            markdown.append('\n');
        }
    }

    /**
     * Renders details for the given tag.
     *
     * @param tagLib     the library which contains the tag
     * @param tag        the name of the tag
     * @param webContext the request to process
     * @throws CompileException in case of an error while rendering the tag template
     */
    @Routed("/system/tag/:1/:2")
    @Permission(PERMISSION_SYSTEM_TAGS)
    public void tagInfo(WebContext webContext, String tagLib, String tag) throws CompileException {
        if ("i".equals(tagLib)) {
            TagHandlerFactory handler = context.findPart("i:" + tag, TagHandlerFactory.class);

            webContext.respondWith()
                      .template("/templates/system/tag.html.pasta",
                                tagLib,
                                tag,
                                handler.reportArguments(),
                                handler.getDescription(),
                                null);
        } else {
            Template template = tagliatelle.resolve("/taglib/" + tagLib + "/" + tag + ".html.pasta")
                                           .orElseThrow(() -> new IllegalArgumentException(tag));
            webContext.respondWith()
                      .template("/templates/system/tag.html.pasta",
                                tagLib,
                                tag,
                                template.getArguments(),
                                template.getPragma("description").asString(),
                                template.getResource().getContentAsString());
        }
    }

    /**
     * Provides some statistics and metrics for the internals of tagliatelle.
     *
     * @param webContext the request being handled
     */
    @Routed("/system/tags/state")
    @Permission(PERMISSION_SYSTEM_TAGS_STATE)
    public void tagState(WebContext webContext) {
        if (webContext.hasParameter("reset")) {
            tagliatelle.getCompiledTemplates().forEach(Template::resetAverageRenderTime);
        }
        webContext.respondWith()
                  .template("/templates/system/tags-state.html.pasta", tagliatelle.getCompiledTemplates());
    }
}
