/*
 * Made with all the love in the world
 * by scireum in Remshalden, Germany
 *
 * Copyright by scireum GmbH
 * http://www.scireum.de - info@scireum.de
 */

package sirius.web.services;

import sirius.kernel.health.ExceptionHint;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks an internal API and specifies which format will be generated.
 * <p>
 * Internal services are not reported as part of the public API ({@link PublicServices}, {@link ApiController}).
 * <p>
 * This annotation can be placed next to a {@link sirius.web.controller.Routed} annotation to mark it as service
 * call. If this annotation is present and {@link Format#JSON} is selected, the method must accept
 * {@link JSONStructuredOutput} as 2nd parameter.  If this annotation is present and {@link Format#XML} is selected,
 * the method must accept {@link sirius.kernel.xml.XMLStructuredOutput} as 2nd parameter. For both outputs, the
 * methods <tt>beginResult</tt> and <tt>endResult</tt> will be called automatically.
 * <p>
 * If the method throws an exception, a response in the appropriate format will be created.
 * Use {@link sirius.web.controller.Controller#ERROR_CODE} and {@link sirius.web.controller.Controller#HTTP_STATUS}
 * to specify a custom error code, or the HTTP status to return
 * (via {@link sirius.kernel.health.Exceptions.ErrorHandler#hint(ExceptionHint, Object)}).
 *
 * @see PublicService
 */
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface InternalService {
    /**
     * Specifies the response format being generated by this service
     *
     * @return the response format of this service
     */
    Format format() default Format.JSON;
}
